#if !canImport(ObjectiveC)
import XCTest

extension HttpLogHandlerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HttpLogHandlerTests = [
        ("testSending", testSending),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HttpLogHandlerTests.__allTests__HttpLogHandlerTests),
    ]
}
#endif
